### PR TITLE
Add options game

### PR DESCRIPTION
**Pull request by acolombo1**
Add features:
- Add a game
- List of games
- List all authors

### CODE REVIEW

**Review by jrosario19 — CHANGES_REQUESTED** [review]
Good Job, so far @acolombo1 .

I have added some suggestions in order to improve your coding skills:
- As you add a Genre when you create a game, kindly add functionality for the option list all genre.

**Comment by acolombo1** [comment]
> Good Job, so far @acolombo1 .
> 
> I have added some suggestions in order to improve your coding skills:
> 
> * As you add a Genre when you create a game, kindly add functionality for the option list all genre.

It is Roberto's task!

**Comment by jrosario19** [comment]
> > Good Job, so far @acolombo1 .
> > I have added some suggestions in order to improve your coding skills:
> > 
> > * As you add a Genre when you create a game, kindly add functionality for the option list all genre.
> 
> It is Roberto's task!

**Review by jrosario19 — COMMENTED** [review]
Understood!! Well implemented!!! Your project is completed, there is nothing else to say, other than it's time to merge it.

**Comment by acolombo1** [comment]
> Understood!! Well implemented!!! Your project is completed, there is nothing else to say, other than it's time to merge it.

Ok, but you closed it, you should have merged it instead of closing it.

**Comment by acolombo1** [comment]
> > Understood!! Well implemented!!! Your project is completed, there is nothing else to say, other than it's time to merge it.
> 
> Ok, but you closed it, you should have merged it instead of closing it.

@jrosario19 Please approve the PR and merge it, it seems to me that you still didn't approve the pull request

**Review by jrosario19 — APPROVED** [review]
Hello @acolombo1 

Your prokect is completed, there is nothing else to say, other than is time to merge it.

**Pull request merged**
